double height = 0;
double width = 0;
double total = 0;
List<String> questions = [
  'What is the value of 3/4 + 1/8? ',
  'Solve for x: 2x - 5 = 15.',
  'Find the area of a rectangle with a length of 12 units and a width of 6 units',
  'Calculate the area of a triangle with a base of 6 units and a height of 8 units.',
  'What is the value of 5^3 (5 raised to the power of 3)?',
  'Simplify: 4(3x - 2) - 2(2x + 5).',
  'If a box contains 24 apples and you take out 3, how many apples are left?',
  'What is the least common multiple (LCM) of 6 and 8?',
  'If the circumference of a circle is 36π (pi) units, what is its radius?',
  'Solve for y: 2y + 7 = 15.',
  'Identify the noun in the following sentence: "The cat chased the mouse."',
  'Which of the following sentences is written in the past tense?',
  'What is the synonym for "joyful"?',
  'In the sentence, "The book is on the shelf," what is the preposition?',
  'Which of the following sentences is a question?',
  'What is the chemical symbol for the element oxygen?',
  'Which planet in our solar system is known as the "Red Planet"?',
  'What is the process by which plants make their own food using sunlight?',
  'Which gas is most abundant in Earth\'s atmosphere?',
  'What is the unit of measurement for electric current?',
  'What is the capital city of Japan?',
  'Who was the first President of the United States?',
  'What is the largest continent by land area?',
  'In which year did Christopher Columbus first arrive in the Americas?',
  'What is the longest river in the world?',
  'If A = 3, B = 6, and C = 9, what is the value of 2A + 3B - C?',
  'What is the next number in the sequence: 1, 4, 9, 16, ___?',
  'If a rectangle has a length of 8 inches and a width of 6 inches, what is its perimeter?',
  'You have Rs. 20, and you buy a book for Rs. 8 and a toy for Rs. 5. How much money do you have left?',
  'If a train travels at a speed of 60 miles per hour and the journey takes 3 hours, how far does it travel?',
  'Who wrote the play "Romeo and Juliet"?',
  'What is the largest planet in our solar system?',
  'Who is the current Prime Minister of the United Kingdom (as of my last knowledge update in September 2021)?',
  'What is the chemical symbol for gold?',
  'Which famous scientist is known for the theory of relativity?',
  'If you need to boil water, which appliance would you most likely use?',
  'What is the first step in washing your hands properly?',
  'How many quarts are in a gallon?',
  'Which tool would you use to tighten a loose screw?',
  'What should you do if you accidentally spill a glass of water on the floor?',
];

List<List<String>> ans = [
  ['5/8', '7/8', '1/2', '1'],
  ['x = 10', 'x = 20', 'x = 5', 'x = 8'],
  ['18 sq units', '72 sq units', '36 sq units', '48 sq units'],
  ['12 square units', '24 square units', '48 square units', '32 square units'],
  ['15', '125', '75', '500'],
  ['6x - 12', '10x - 14', '6x + 12', '10x + 14'],
  ['24', '21', '3', '27'],
  ['12', '18', '24', '48'],
  ['6 units', '9 units', '12 units', '18 units'],
  ['y = 4', 'y = 8', 'y = 14', 'y = 5'],
  ['cat', 'chased', 'the', 'mouse'],
  [
    'She is eating dinner',
    'They will go to the park',
    'He walked to school',
    'We are playing games'
  ],
  ['Sad', 'Angry', 'Happy', 'Excited'],
  ['is', 'on', 'the', 'book'],
  [
    'It is sunny outside',
    'She ate lunch at noon',
    'Are you coming to the party?',
    'They play soccer after school.'
  ],
  ['O', 'Ox', 'Oxg', 'Om'],
  ['Earth', 'Mars', 'Venus', 'Jupiter'],
  ['Photosynthesis', 'Digestion', 'Respiration', 'Transpiration'],
  ['Nitrogen', 'Oxygen', 'Carbon dioxide', 'Hydrogen'],
  ['Amperes', 'Ohms', 'Watts', 'Volts'],
  ['Tokyo', 'Beijing', 'Seoul', 'Bangkok'],
  ['George Washington', 'John Adams', 'Thomas Jefferson', 'Abraham Lincoln'],
  ['Africa', 'Asia', 'North America', 'Europe'],
  ['1492', '1620', '1776', '1865'],
  ['Amazon river', 'Nile river', 'Mississippi river', 'Yangtze river'],
  ['9', '12', '15', '8'],
  ['20', '25', '32', '36'],
  ['12 inches', '14 inches', '24 inches', '28 inches'],
  ['Rs. 7', 'Rs. 12', 'Rs. 5', 'Rs. 3'],
  ['120 miles', '180 miles', '240 miles', '360 miles'],
  ['William Shakespeare', 'Charles Dickens', 'Jane Austen', 'Mark Twain'],
  ['Earth', 'Mars', 'Venus', 'Jupiter'],
  ['Boris Johnson', 'Theresa May', 'David Cameron', 'Tony Blair'],
  ['Go', 'Gd', 'Au', 'Ag'],
  ['Issac Newton', 'Galileo Galilei', 'Albert Einstein', 'Stephen Hawking'],
  ['Toaster', 'Microwave', 'Blender', 'Kettle'],
  [
    'Dry your hands with water',
    'Rinse your hands with water',
    'Apply soap to your hands',
    'Shake hands vigorously'
  ],
  ['2', '4', '8', '16'],
  ['Screwdriver', 'Pliers', 'Wrench', 'Hammer'],
  [
    'Wipe it up with a towel or mop.',
    'Leave it and let it evaporate',
    'Step over it and continue walking',
    'Ignore it; it will dry on its own.'
  ],
];

List<String> CorrectAns = [
  '7/8',
  'x = 10',
  '36 sq units',
  '24 square units',
  '125',
  '6x - 12',
  '21',
  '24',
  '9 units',
  'y = 4',
  'cat',
  'He walked to school',
  'Happy',
  'on',
  'Are you coming to the party?',
  'O',
  'Mars',
  'Photosynthesis',
  'Nitrogen',
  'Amperes',
  'Tokyo',
  'George Washington',
  'Asia',
  '1492',
  'Nile river',
  '15',
  '25',
  '24 inches',
  'Rs. 7',
  '120 miles',
  'William Shakespeare',
  'Jupiter',
  'Boris Johnson',
  'Au',
  'Albert Einstein',
  'Kettle',
  'Apply soap to your hands',
  '4',
  'Screwdriver',
  'Wipe it up with a towel or mop.',
];
List<int> marks = [];
List<String> Selected = [];

String Fname = "";
String Fage = "";
String Femail = "";
String Fphone = "";
String Fcity = "";
int group = 0;

List<String> questions2 = [
  'Calculate the derivative of f(x) = 2x^3 - 6x^2 + 4x - 1.',
  'Solve the equation: log(x) = 2.',
  'What is the value of the integral ∫(2x + 3) dx from 0 to 4?',
  'Find the solution to the system of equations: 3x - 2y = 7 2x + y = 5',
  'What is the value of sin(π/3)?',
  'If a right triangle has one angle of 30 degrees, what is the measure of the other acute angle?',
  'Evaluate: √(16) + √(25) - √(9).',
  'Calculate the value of 5! (5 factorial).',
  'Find the solution to the equation: |2x - 5| = 7.',
  'If a circle has a radius of 6 inches, what is its circumference?',
  'Identify the literary device used in the sentence: "The stars danced in the night sky."',
  'In Shakespeare\'s play "Macbeth," what is the name of the three witches who make predictions?',
  'Which of the following is an example of a tragic flaw in literature?',
  'What literary term describes the repetition of consonant sounds at the beginning of words in a sentence?',
  'Who is the author of the novel "Pride and Prejudice"?',
  'What is the chemical symbol for the element iron?',
  'Which gas is responsible for the green color in plants\' leaves during photosynthesis?',
  'What is the process by which plants lose water vapor through tiny openings in their leaves?',
  'Which planet in our solar system has the largest number of moons?',
  'What is the unit of measurement for electric resistance?',
  'Who is often credited with the invention of the World Wide Web?',
  'What was the major event that marked the beginning of World War I?',
  'Which country is known as the "Land of the Rising Sun"?',
  'Who was the first woman to fly solo across the Atlantic Ocean?',
  'Which document begins with the words, "We the People"?',
  'If a car travels at a constant speed of 60 miles per hour, how long does it take to travel 120 miles?',
  'What is the next number in the sequence: 1, 4, 9, 16, _?',
  'If a box contains 24 red balls and 16 blue balls, what is the probability of randomly selecting a red ball?',
  'What is the square root of 144?',
  'If a triangle has angles measuring 45 degrees, 45 degrees, and 90 degrees, what type of triangle is it?',
  'Who wrote the play "Hamlet"?',
  'What is the longest river in the world?',
  'Which gas makes up the majority of Earth\'s atmosphere?',
  'Who is the author of the novel "To Kill a Mockingbird"?',
  'What is the chemical symbol for the element gold?',
  'What is the first step in performing CPR (Cardiopulmonary Resuscitation)?',
  'How do you properly use a fire extinguisher in case of a small fire?',
  'Which of the following is a common method for conserving energy in a household?',
  'What should you do if someone is choking and cannot breathe or speak?',
  'How should you safely handle a knife in the kitchen?',
];

List<List<String>> options2 = [
  [
    '6x^2 - 12x + 4',
    '6x^2 - 12x + 3',
    '3x^2 - 6x + 2',
    '2x^4 - 6x^3 + 4x^2 - 1'
  ],
  ['x = 0', 'x = 1', 'x = 10', 'x = 100'],
  ['14', '16', '18', '20'],
  ['x = 3, y = -1', 'x = 2, y = 1', 'x = 1, y = 2', 'x = 0, y = 3'],
  ['√2/2', '√3/2', '1-2', '1'],
  ['30 degrees', '45 degrees', '60 degrees', '90 degrees'],
  ['10', '11', '12', '14'],
  ['10', '20', '120', '60'],
  ['x = -1', 'x = 6', 'x = 1', 'x = 4'],
  ['6π inches', '12π inches', '18π inches', '36π inches'],
  ['Smile', 'Metaphor', 'Personification', 'Hyperbole'],
  [
    'The Weird Sisters',
    'The Enchanting Trio',
    'The Mystic Coven',
    'The Spellbinding Witches'
  ],
  [
    'A character\'s kindness',
    'A character\'s intelligence',
    'A character\'s excessive pride',
    'A character\'s loyalty'
  ],
  ['Smile', 'Alliteration', 'Hyperbole', 'Onomatopoeia'],
  ['Charles Dickens', 'Jane Austen', 'Emily Brontë', 'Leo Tolstoy'],
  ['Ir', 'In', 'Fe', 'Fi'],
  ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Chlorophyll'],
  ['Photosynthesis', 'Transpiration', 'Respiration', 'Fermentation'],
  ['Earth', 'Jupiter', 'Saturn', 'Mars'],
  ['Ohms', 'Volts', 'Amperes', 'Watts'],
  ['Bill Gates', 'Tim Berners-Lee', 'Steve Jobs', 'Mark Zuckerberg'],
  [
    'The sinking of the Titanic',
    'The assassination of Archduke Franz Ferdinand',
    'The signing of the Treaty of Versailles',
    'The Battle of Stalingrad'
  ],
  ['China', 'India', 'Japan', 'South Korea'],
  ['Amelia Earhart', 'Bessie Coleman', 'Harriet Quimby', 'Sally Ride'],
  [
    'The Declaration of Independence',
    'The Gettysburg Address',
    'The U.S. Constitution',
    'The Bill of Rights'
  ],
  ['1 hour', '2 hour', '3 hour', '4 hour'],
  ['20', '25', '36', '49'],
  ['1-2', '2-3', '3-4', '4-5'],
  ['12', '16', '10', '14'],
  ['Equilateral', 'Isosceles', 'Scalene', 'Right'],
  [
    'William Shakespeare',
    'George Orwell',
    'F. Scott Fitzgerald',
    'Charles Dickens'
  ],
  ['Amazon River', 'Nile River', 'Mississippi River', 'Yangtze River'],
  ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'],
  ['Harper Lee', 'Mark Twain', 'J.K. Rowling', 'George Orwell'],
  ['Go', 'Gd', 'Au', 'Ag'],
  [
    'Call 911',
    'Check for breathing',
    'Begin chest compressions',
    'Tilt the head back'
  ],
  [
    'Spray it in the air',
    'Aim at the base of the fire and squeeze the handle',
    'Pour water on the fire',
    'Shake it vigorously before use'
  ],
  [
    'Leaving lights on when not needed',
    'Setting the thermostat to a very high temperature in winter',
    'Using energy-efficient light bulbs',
    'Running appliances on their highest settings'
  ],
  [
    'Offer them water to drink',
    'Perform the Heimlich maneuver',
    'Hit them on the back',
    'Ignore them and wait for help'
  ],
  [
    'Hold it with the blade facing outward',
    'Carry it by the handle with the blade down',
    'Use it for tasks it\'s not designed for',
    'Leave it on the edge of the counter'
  ],
];

List<String> answers2 = [
  '6x^2 - 12x + 4',
  'x = 100',
  '16',
  'x = 3, y = -1',
  '√3/2',
  '60 degrees',
  '10',
  '120',
  'x = 6',
  '12π inches',
  'Personification',
  'The Weird Sisters',
  'A character\'s excessive pride',
  'Alliteration',
  'Jane Austen',
  'Fe',
  'Chlorophyll',
  'Transpiration',
  'Jupiter',
  'Ohms',
  'Tim Berners-Lee',
  'The assassination of Archduke Franz Ferdinand',
  'Japan',
  'Amelia Earhart',
  'The U.S. Constitution',
  '2 hour',
  '25',
  '2-3',
  '12',
  'Isosceles',
  'William Shakespeare',
  'Nile River',
  'Nitrogen',
  'Harper Lee',
  'Au',
  'Call 911',
  'Aim at the base of the fire and squeeze the handle',
  'Using energy-efficient light bulbs',
  'Perform the Heimlich maneuver',
  'Hold it with the blade facing outward',
];

List<String> questions1 = [];
List<List<String>> options1 = [];
List<String> answers1 = [];
// Create a User object with the retrieved data

